apiVersion: metrics.keptn.sh/v1alpha2
kind: KeptnMetric
metadata:
  name: consumed-memory
  namespace: podtato-kubectl
spec:
  provider: 
    name: prometheus
  query: "sum(kube_node_status_capacity{resource='memory'})"
  fetchIntervalSeconds: 10
