apiVersion: v2
name: keptn
description: >-
  A Helm chart for Keptn, a set of tools to enable cloud-native application
  lifecycle management
icon: >-
  https://raw.githubusercontent.com/cncf/artwork/master/projects/keptn/icon/color/keptn-icon-color.svg
home: https://keptn.sh
sources:
  - https://github.com/keptn/lifecycle-toolkit
keywords:
  - cloud-native
  - lifecycle
  - lifecycle-management
  - application-lifecycle
  - application-lifecycle-management
  - orchestration
  - keptn
  - operator
  - pre-deployment
  - post-deployment
  - metrics
  - analysis
  - evaluation
  - certificate
annotations:
  artifacthub.io/links: |
    - name: support
      url: https://github.com/keptn/lifecycle-toolkit/issues/new
    - name: community
      url: https://slack.keptn.sh/
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: 'true'
  artifacthub.io/operatorCapabilities: Full Lifecycle
kubeVersion: '>= 1.27.0-0'
type: application
version: 0.10.0 # Helm Chart version
appVersion: v2.4.0 # x-release-please-version
dependencies:
  - name: keptn-cert-manager
    version: 0.3.0
    alias: certManager
    condition: global.certManagerEnabled
    repository: file://../keptn-cert-manager/chart
  - name: keptn-lifecycle-operator
    version: 0.6.0
    alias: lifecycleOperator
    condition: lifecycleOperator.enabled
    repository: file://../lifecycle-operator/chart
  - name: keptn-metrics-operator
    version: 0.5.0
    alias: metricsOperator
    condition: metricsOperator.enabled
    repository: file://../metrics-operator/chart
