documentation:
  - docs/**/*
  - "**/*.md"

lifecycle-operator:
  - lifecycle-operator/**/*

scheduler:
  - scheduler/**/*

metrics-operator:
  - metrics-operator/**/*

cert-manager:
  - klt-cert-manager/**/*

ops:
  - .github/**/*
  - netlify.toml
  - .markdownlint-cli2.yml

helm:
  - helm/**/*
