config:
  ul-indent:
    indent: 4
  line-length:
    line_length: 120
    tables: false
    code_blocks: false
  code-block-style:
    style: fenced
  no-inline-html:
    allowed_elements:
      - details
      - summary
  github-admonition: true
  max-one-sentence-per-line: true

customRules:
  - ".github/actions/markdown-lint-rules/max-one-sentence-per-line.js"

ignores:
  - "**/CHANGELOG.md"
  - "node_modules"
  - "readme-generator-for-helm"
