{
 "title": "Keptn Applications",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": {
     "query": "label_values(keptn_deployment_app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Time between Deployments",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_workload_previousversion, keptn_deployment_workload_version) (keptn_app_deploymentinterval{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(keptn_app_count{keptn_deployment_app_name=\"$Application\", keptn_deployment_app_status=\"Succeeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(keptn_app_active{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(keptn_deployment_count{keptn_deployment_app_name=\"$Application\", keptn_deployment_app_status=\"Failed\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "keptn_app_count{keptn_deployment_app_name=\"$Application\", keptn_deployment_app_status=\"Failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(keptn_deployment_app_version) (keptn_app_duration_bucket{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "{{keptn_workload_version}}"
    }
   ]
  },
  {
   "title": "Deployments Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 14 },
   "targets": [
    {
     "expr": "max(keptn_app_active{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time between Deployments",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_app_previousversion, keptn_deployment_app_version) (keptn_app_deploymentinterval{keptn_deployment_app_name=\"$Application\"})",
     "legendFormat": "{{keptn_deployment_app_previousversion}} - {{keptn_deployment_app_version}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "operation": "AppDeploy",
     "service": "keptn-lifecycle-operator",
     "tags": "keptn.deployment.app.name=$Application"
    }
   ]
  }
 ]
}