name: "Deploy Keptn Lifecycle Toolkit on GH cluster"
description: "Creates a Kind cluster and deploys Keptn Lifecycle Toolkit"
inputs:
  kind-version:
    required: false
    description: "Version of kind that should be used"
    # renovate: datasource=github-releases depName=kubernetes-sigs/kind
    default: "v0.17.0"
  k8s-version:
    required: false
    description: "Kubernetes that should be used"
    # renovate: datasource=github-releases depName=kubernetes/kubernetes
    default: "v1.25.3"
  functions_runtime_tag:
    description: "Tag for the functions runner image"
    required: true
  cluster-name:
    required: false
    description: "Name of the kind cluster"
    default: "test-cluster"
  helm-install:
    required: false
    type: boolean
    description: "Install KLT via helm instead of manifest if true"
    # renovate: datasource=github-releases depName=kubernetes-sigs/kind
    default: false
runs:
  using: "composite"
  steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: '**/go.sum'

    - name: Download manifests
      uses: actions/download-artifact@v3
      with:
        path: ~/download/artifacts

    - name: "Create single kind Cluster"
      uses: helm/kind-action@v1.5.0
      with:
        cluster_name: ${{ inputs.cluster-name }}
        version: ${{ inputs.kind-version }}
        node_image: "kindest/node:${{ inputs.k8s-version }}"
        kubectl_version: ${{ inputs.k8s-version }}

    - name: Import images in k3d
      shell: bash
      run: |
        cd ~/download/artifacts
        for image in $(ls | grep image.tar);
        do
          echo "Importing image: $image"
          kind load image-archive $image/$image -n ${{ inputs.cluster-name }}
        done

    - name: Install lifecycle-toolkit with manifests
      if: ${{ inputs.helm-install == 'false' }}
      shell: bash
      run: |
        echo "Installing KLT using manifests"
        sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/lifecycle-operator-manifest-test/release.yaml
        sed -i 's/ghcr.keptn.sh\/keptn\/functions-runtime:.*/localhost:5000\/keptn\/functions-runtime:${{ inputs.functions_runtime_tag }}/g' ~/download/artifacts/lifecycle-operator-manifest-test/release.yaml
        kubectl create namespace keptn-lifecycle-toolkit-system
        kubectl apply -f ~/download/artifacts/lifecycle-operator-manifest-test
        
        sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/certificate-operator-manifest-test/release.yaml
        kubectl apply -f ~/download/artifacts/certificate-operator-manifest-test
        kubectl rollout status deployment certificate-operator -n keptn-lifecycle-toolkit-system -w

        sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/metrics-operator-manifest-test/release.yaml
        kubectl apply -f ~/download/artifacts/metrics-operator-manifest-test
        kubectl rollout status deployment metrics-operator -n keptn-lifecycle-toolkit-system -w
        
        sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/scheduler-manifest-test/release.yaml
        kubectl apply -f ~/download/artifacts/scheduler-manifest-test
        kubectl rollout status deployment scheduler -n keptn-lifecycle-toolkit-system -w
        kubectl rollout status deployment lifecycle-operator -n keptn-lifecycle-toolkit-system -w

    - name: Install lifecycle-toolkit with helm
      if: ${{ inputs.helm-install == 'true'  }}
      shell: bash
      run: |
        echo "Installing KLT using helm"
        helm version
        helm install -n keptn-lifecycle-toolkit-system --create-namespace toolkit ~/download/artifacts/keptn-lifecycle-toolkit.tgz \
        --set scheduler.scheduler.imagePullPolicy=Never \
        --set lifecycleOperator.manager.imagePullPolicy=Never \
        --set metricsOperator.manager.imagePullPolicy=Never \
        --set lifecycleOperator.manager.env.functionRunnerImage=localhost:5000/keptn/functions-runtime:${{ inputs.functions_runtime_tag }} \
        --set certificateOperator.manager.imagePullPolicy=Never \
        --debug --wait --timeout 1m
