name: "Deploy Keptn Lifecycle Toolkit on GH cluster"
description: "Creates a Kind cluster and deploys Keptn Lifecycle Toolkit"
inputs:
  kind-version:
    required: false
    description: "Version of kind that should be used"
    # renovate: datasource=github-releases depName=kubernetes-sigs/kind
    default: "v0.18.0"
  k8s-version:
    required: false
    description: "Kubernetes version that should be used"
    # renovate: datasource=github-releases depName=kubernetes/kubernetes
    default: "v1.27.3"
  runtime_tag:
    description: "Tag for the runner image"
    required: true
  cluster-name:
    required: false
    description: "Name of the kind cluster"
    default: "test-cluster"
  helm-install:
    required: false
    description: "Install Keptn via helm instead of manifest if true"
    default: "helm_on"
  scheduling-gates:
    required: false
    description: "Use scheduling gates instead of scheduler"
    default: "gates_off"
  allowed-namespaces:
    required: false
    description: "Decides whether to allow only certain namespaces"
    default: "allowed_ns_off"
runs:
  using: "composite"
  steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: '**/go.sum'
        check-latest: true

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ~/download/artifacts

    - name: "Create single kind Cluster"
      uses: helm/kind-action@v1.8.0
      with:
        cluster_name: ${{ inputs.cluster-name }}
        version: ${{ inputs.kind-version }}
        node_image: "kindest/node:${{ inputs.k8s-version }}"
        kubectl_version: ${{ inputs.k8s-version }}

    - name: Import images in k3d
      shell: bash
      run: |
        cd ~/download/artifacts
        for image in $(ls | grep image.tar);
        do
          echo "Importing image: $image"
          kind load image-archive $image/$image -n ${{ inputs.cluster-name }}
        done

    - name: Install lifecycle-toolkit with manifests
      if: ${{  inputs.helm-install == 'helm_off' }}
      shell: bash
      run: |
        echo "Installing Keptn using manifests"
        sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/lifecycle-operator-manifest-test/release.yaml
        sed -i 's/ghcr.io\/keptn\/deno-runtime:.*/localhost:5000\/keptn\/deno-runtime:${{ inputs.runtime_tag }}/g' \
          ~/download/artifacts/lifecycle-operator-manifest-test/release.yaml
        sed -i 's/ghcr.io\/keptn\/python-runtime:.*/localhost:5000\/keptn\/python-runtime:${{ inputs.runtime_tag }}/g' \
          ~/download/artifacts/lifecycle-operator-manifest-test/release.yaml
        kubectl create namespace keptn-lifecycle-toolkit-system
        kubectl apply -f ~/download/artifacts/lifecycle-operator-manifest-test

        sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/certificate-operator-manifest-test/release.yaml
        kubectl apply -f ~/download/artifacts/certificate-operator-manifest-test
        kubectl rollout status deployment certificate-operator -n keptn-lifecycle-toolkit-system -w

        sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/metrics-operator-manifest-test/release.yaml
        kubectl apply -f ~/download/artifacts/metrics-operator-manifest-test
        kubectl rollout status deployment metrics-operator -n keptn-lifecycle-toolkit-system -w

        sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/scheduler-manifest-test/release.yaml
        kubectl apply -f ~/download/artifacts/scheduler-manifest-test
        kubectl rollout status deployment scheduler -n keptn-lifecycle-toolkit-system -w
        kubectl rollout status deployment lifecycle-operator -n keptn-lifecycle-toolkit-system -w

    - name: Install lifecycle-toolkit with helm
      if: ${{ inputs.helm-install == 'helm_on' }}
      env:
        RELEASE_REGISTRY: "localhost:5000/keptn"
      shell: bash
      run: |
        echo "Installing Keptn using helm"
        helm version

        cd ./lifecycle-operator/chart 
        helm dependency update
        helm dependency build 
        
        cd ../../metrics-operator/chart 
        helm dependency update
        helm dependency build 
        
        cd ../../klt-cert-manager/chart 
        helm dependency update
        helm dependency build
        
        cd ../../chart
        helm dependency update
        helm dependency build

        touch tmp-values.yaml
        if [ "${{ inputs.allowed-namespaces }}" == "allowed_ns_on" ]; then
          echo "lifecycleOperator:" >> tmp-values.yaml
          echo "  allowedNamespaces: [allowed-ns-test]" >> tmp-values.yaml
        fi

        if [ "${{ inputs.scheduling-gates }}" == "gates_on" ]; then
          if [ "${{ inputs.allowed-namespaces }}" == "allowed_ns_off" ]; then
            echo "lifecycleOperator:" >> tmp-values.yaml
          fi
          echo "  schedulingGatesEnabled: true" >> tmp-values.yaml
        fi

        helm install -n keptn-lifecycle-toolkit-system --create-namespace keptn ./ \
          --values tmp-values.yaml \
          --set lifecycleOperator.scheduler.imagePullPolicy=Never \
          --set lifecycleOperator.scheduler.image.tag=${{ inputs.runtime_tag }} \
          --set lifecycleOperator.scheduler.image.repository="localhost:5000/keptn/scheduler" \
          --set lifecycleOperator.lifecycleOperator.imagePullPolicy=Never \
          --set lifecycleOperator.lifecycleOperator.image.tag=${{ inputs.runtime_tag }} \
          --set lifecycleOperator.lifecycleOperator.image.repository="localhost:5000/keptn/lifecycle-operator" \
          --set lifecycleOperator.lifecycleOperator.env.functionRunnerImage=localhost:5000/keptn/deno-runtime:${{ inputs.runtime_tag }} \
          --set lifecycleOperator.lifecycleOperator.env.pythonRunnerImage=localhost:5000/keptn/python-runtime:${{ inputs.runtime_tag }} \
          --set certManager.imagePullPolicy=Never \
          --set certManager.image.tag=${{ inputs.runtime_tag }} \
          --set certManager.image.repository="localhost:5000/keptn/certificate-operator" \
          --set metricsOperator.imagePullPolicy=Never \
          --set metricsOperator.env.enableKeptnAnalysis="true" \
          --set metricsOperator.image.tag=${{ inputs.runtime_tag }} \
          --set metricsOperator.image.repository="localhost:5000/keptn/metrics-operator" \
          --debug --wait --timeout 1m
