name: "Deploy Keptn Lifecycle Toolkit on GH cluster"
description: "Creates a Kind cluster and deploys Keptn Lifecycle Toolkit"
inputs:
   cert-manager-version:
     required: true
     description: "Version of cert-manager that should be deployed"
   k3d-version:
     required: true
     description: "Version of k3d that should be used"
runs:
  using: "composite"
  steps:
  - name: Set up Go 1.x
    uses: actions/setup-go@v3
    with:
      go-version: ${{ env.GO_VERSION }}
      cache: true
      cache-dependency-path: '**/go.sum'

  - name: Download manifests
    uses: actions/download-artifact@v3
    with:
      path: ~/download/artifacts

  - name: "Create single k3d Cluster"
    uses: AbsaOSS/k3d-action@v2
    with:
      cluster-name: test-cluster
      k3d-version: ${{ inputs.k3d-version }}
      args: >-
        --agents 1
        --no-lb
        --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"

  - name: Import images in k3d
    shell: bash
    run: |
      cd ~/download/artifacts
      for image in $(ls | grep image.tar);
      do
        echo "Importing image: $image"
        k3d image import $image/$image -c test-cluster
      done
  
  - name: Install cert-manager
    shell: bash
    run: |
      kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/${{ inputs.cert-manager-version }}/cert-manager.yaml
      kubectl rollout status deployment cert-manager-cainjector -n cert-manager -w
      kubectl rollout status deployment cert-manager-webhook -n cert-manager -w
      kubectl rollout status deployment cert-manager -n cert-manager -w
    
  - name: Install lifecycle-toolkit
    shell: bash
    run: |
      sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/g' ~/download/artifacts/keptn-lifecycle-operator-manifest-test/keptn-lifecycle-operator-manifest-test
      kubectl apply -f ~/download/artifacts/keptn-lifecycle-operator-manifest-test
      kubectl apply -f ~/download/artifacts/scheduler-manifest-test
      sleep 5
      docker exec k3d-test-cluster-server-0 sh -c "ctr image list | grep localhost"
      kubectl describe pod --selector control-plane=controller-manager -n keptn-lifecycle-toolkit-system
      kubectl describe pod --selector component=scheduler -n keptn-lifecycle-toolkit-system
      kubectl rollout status deployment keptn-scheduler -n keptn-lifecycle-toolkit-system -w
      kubectl rollout status deployment klc-controller-manager -n keptn-lifecycle-toolkit-system -w
