name: "Deploy Keptn Lifecycle Toolkit on GH cluster"
description: "Creates a Kind cluster and deploys Keptn Lifecycle Toolkit"
inputs:
  kind-version:
    required: false
    description: "Version of kind that should be used"
    # renovate: datasource=github-releases depName=kubernetes-sigs/kind
    default: "v0.18.0"
  k8s-version:
    required: false
    description: "Kubernetes version that should be used"
    # renovate: datasource=github-releases depName=kubernetes/kubernetes
    default: "v1.27.3"
  runtime_tag:
    description: "Tag for the runner image"
    required: true
  cluster-name:
    required: false
    description: "Name of the kind cluster"
    default: "test-cluster"
  scheduling-gates:
    required: false
    description: "Use scheduling gates instead of scheduler"
    default: "gates_off"
  allowed-namespaces:
    required: false
    description: "Decides whether to allow only certain namespaces"
    default: "allowed_ns_off"
runs:
  using: "composite"
  steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: '**/go.sum'
        check-latest: true

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ~/download/artifacts

    - name: "Create single kind Cluster"
      uses: helm/kind-action@v1.8.0
      with:
        cluster_name: ${{ inputs.cluster-name }}
        version: ${{ inputs.kind-version }}
        node_image: "kindest/node:${{ inputs.k8s-version }}"
        kubectl_version: ${{ inputs.k8s-version }}

    - name: Import images in k3d
      shell: bash
      run: |
        cd ~/download/artifacts
        for image in $(ls | grep image.tar);
        do
          echo "Importing image: $image"
          kind load image-archive $image/$image -n ${{ inputs.cluster-name }}
        done

    - name: Install lifecycle-toolkit with helm
      env:
        RELEASE_REGISTRY: "localhost:5000/keptn"
      shell: bash
      run: |
        echo "Installing Keptn using helm"
        helm version

        helm repo add keptn "https://charts.lifecycle.keptn.sh"
        helm repo update

        for chart_dir in ./lifecycle-operator/chart \
                ./metrics-operator/chart \
                ./klt-cert-manager/chart \
                ./chart; do
            cd "$chart_dir"
            echo "updating charts for" $chart_dir
            helm dependency update
            helm dependency build
            cd -  # Return to the previous directory
        done

        cd .github/actions/deploy-klt-on-cluster

        if [ "${{ inputs.allowed-namespaces }}" == "allowed_ns_on" ]; then
          echo "  allowedNamespaces: [allowed-ns-test]" >> values.yaml
        fi

        if [ "${{ inputs.scheduling-gates }}" == "gates_on" ]; then
          echo "  schedulingGatesEnabled: true" >> values.yaml
        fi
        echo "installing with values.yaml file:"
        cat values.yaml

        cd ../../../chart

        helm install -n keptn-lifecycle-toolkit-system --create-namespace keptn ./ \
          --values ../.github/actions/deploy-klt-on-cluster/values.yaml \
          --set lifecycleOperator.scheduler.image.tag=${{ inputs.runtime_tag }} \
          --set lifecycleOperator.lifecycleOperator.image.tag=${{ inputs.runtime_tag }} \
          --set lifecycleOperator.lifecycleOperator.env.functionRunnerImage=localhost:5000/keptn/deno-runtime:${{ inputs.runtime_tag }} \
          --set lifecycleOperator.lifecycleOperator.env.pythonRunnerImage=localhost:5000/keptn/python-runtime:${{ inputs.runtime_tag }} \
          --set certManager.image.tag=${{ inputs.runtime_tag }} \
          --set metricsOperator.image.tag=${{ inputs.runtime_tag }} \
          --debug --wait --timeout 1m
