---
apiVersion: lifecycle.keptn.sh/v1
kind: KeptnAppContext
metadata:
  name: podtato-head
  namespace: podtato-kubectl
spec:
  preDeploymentEvaluations:
    - app-pre-deploy-eval-2
  preDeploymentTasks:
    - container-sleep
    - python-secret
  promotionTasks:
    - promotion
