apiVersion: lifecycle.keptn.sh/v1
kind: KeptnApp
metadata:
  annotations:
    app.kubernetes.io/managed-by: keptn
  creationTimestamp: null
  name: some-keptn-app
  namespace: my-app-ns
spec:
  version: 1.2.3
  workloads:
    - name: podtato-head-left-arm
      version: 0.2.7
status: {}

---
apiVersion: lifecycle.keptn.sh/v1
kind: KeptnAppContext
metadata:
  creationTimestamp: null
  name: some-keptn-app
  namespace: my-app-ns
spec:
  postDeploymentEvaluations:
    - post-deployment-evaluation
  postDeploymentTasks:
    - post-deployment-task
  preDeploymentEvaluations:
    - pre-deployment-evaluation
  preDeploymentTasks:
    - pre-deployment-task
status: {}
