authors:
  mowies:
    name: Moritz Wiesinger
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/6901203?v=4
    url: https://github.com/mowies
  bacherfl:
    name: Florian Bacher
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/2143586?v=4
    url: https://github.com/bacherfl
  odubajDT:
    name: Ondrej Dubaj
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/93584209?v=4
    url: https://github.com/odubajDT
  staceypotter:
    name: Stacey Potter
    description: Member
    avatar: https://avatars.githubusercontent.com/u/50154848?v=4
    url: https://github.com/staceypotter
  agardnerit:
    name: Adam Gardner
    description: Member
    avatar: https://avatars.githubusercontent.com/u/26523841?v=4
    url: https://github.com/agardnerit
