// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fake

import (
	"github.com/keptn/lifecycle-toolkit/operator/apis/lifecycle/v1alpha3"
	"sync"
)

// ICriteriaMock is a mock implementation of analysis.ICriteria.
//
//	func TestSomethingThatUsesICriteria(t *testing.T) {
//
//		// make and configure a mocked analysis.ICriteria
//		mockedICriteria := &ICriteriaMock{
//			EvaluateFunc: func(val float64) v1alpha3.CriteriaResult {
//				panic("mock out the Evaluate method")
//			},
//		}
//
//		// use mockedICriteria in code that requires analysis.ICriteria
//		// and then make assertions.
//
//	}
type ICriteriaMock struct {
	// EvaluateFunc mocks the Evaluate method.
	EvaluateFunc func(val float64) v1alpha3.CriteriaResult

	// calls tracks calls to the methods.
	calls struct {
		// Evaluate holds details about calls to the Evaluate method.
		Evaluate []struct {
			// Val is the val argument value.
			Val float64
		}
	}
	lockEvaluate sync.RWMutex
}

// Evaluate calls EvaluateFunc.
func (mock *ICriteriaMock) Evaluate(val float64) v1alpha3.CriteriaResult {
	if mock.EvaluateFunc == nil {
		panic("ICriteriaMock.EvaluateFunc: method is nil but ICriteria.Evaluate was just called")
	}
	callInfo := struct {
		Val float64
	}{
		Val: val,
	}
	mock.lockEvaluate.Lock()
	mock.calls.Evaluate = append(mock.calls.Evaluate, callInfo)
	mock.lockEvaluate.Unlock()
	return mock.EvaluateFunc(val)
}

// EvaluateCalls gets all the calls that were made to Evaluate.
// Check the length with:
//
//	len(mockedICriteria.EvaluateCalls())
func (mock *ICriteriaMock) EvaluateCalls() []struct {
	Val float64
} {
	var calls []struct {
		Val float64
	}
	mock.lockEvaluate.RLock()
	calls = mock.calls.Evaluate
	mock.lockEvaluate.RUnlock()
	return calls
}
