// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fake

import (
	"github.com/keptn/lifecycle-toolkit/operator/apis/lifecycle/v1alpha3"
	"sync"
)

// ICriteriaEvaluatorMock is a mock implementation of analysis.ICriteriaEvaluator.
//
//	func TestSomethingThatUsesICriteriaEvaluator(t *testing.T) {
//
//		// make and configure a mocked analysis.ICriteriaEvaluator
//		mockedICriteriaEvaluator := &ICriteriaEvaluatorMock{
//			EvaluateFunc: func(val float64, criteria v1alpha3.Criteria) v1alpha3.CriteriaResult {
//				panic("mock out the Evaluate method")
//			},
//		}
//
//		// use mockedICriteriaEvaluator in code that requires analysis.ICriteriaEvaluator
//		// and then make assertions.
//
//	}
type ICriteriaEvaluatorMock struct {
	// EvaluateFunc mocks the Evaluate method.
	EvaluateFunc func(val float64, criteria v1alpha3.Criteria) v1alpha3.CriteriaResult

	// calls tracks calls to the methods.
	calls struct {
		// Evaluate holds details about calls to the Evaluate method.
		Evaluate []struct {
			// Val is the val argument value.
			Val float64
			// Criteria is the criteria argument value.
			Criteria v1alpha3.Criteria
		}
	}
	lockEvaluate sync.RWMutex
}

// Evaluate calls EvaluateFunc.
func (mock *ICriteriaEvaluatorMock) Evaluate(val float64, criteria v1alpha3.Criteria) v1alpha3.CriteriaResult {
	if mock.EvaluateFunc == nil {
		panic("ICriteriaEvaluatorMock.EvaluateFunc: method is nil but ICriteriaEvaluator.Evaluate was just called")
	}
	callInfo := struct {
		Val      float64
		Criteria v1alpha3.Criteria
	}{
		Val:      val,
		Criteria: criteria,
	}
	mock.lockEvaluate.Lock()
	mock.calls.Evaluate = append(mock.calls.Evaluate, callInfo)
	mock.lockEvaluate.Unlock()
	return mock.EvaluateFunc(val, criteria)
}

// EvaluateCalls gets all the calls that were made to Evaluate.
// Check the length with:
//
//	len(mockedICriteriaEvaluator.EvaluateCalls())
func (mock *ICriteriaEvaluatorMock) EvaluateCalls() []struct {
	Val      float64
	Criteria v1alpha3.Criteria
} {
	var calls []struct {
		Val      float64
		Criteria v1alpha3.Criteria
	}
	mock.lockEvaluate.RLock()
	calls = mock.calls.Evaluate
	mock.lockEvaluate.RUnlock()
	return calls
}
