//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnWorkload) DeepCopyInto(out *KeptnWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnWorkload.
func (in *KeptnWorkload) DeepCopy() *KeptnWorkload {
	if in == nil {
		return nil
	}
	out := new(KeptnWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnWorkloadInstance) DeepCopyInto(out *KeptnWorkloadInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnWorkloadInstance.
func (in *KeptnWorkloadInstance) DeepCopy() *KeptnWorkloadInstance {
	if in == nil {
		return nil
	}
	out := new(KeptnWorkloadInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnWorkloadInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnWorkloadInstanceList) DeepCopyInto(out *KeptnWorkloadInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnWorkloadInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnWorkloadInstanceList.
func (in *KeptnWorkloadInstanceList) DeepCopy() *KeptnWorkloadInstanceList {
	if in == nil {
		return nil
	}
	out := new(KeptnWorkloadInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnWorkloadInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnWorkloadInstanceSpec) DeepCopyInto(out *KeptnWorkloadInstanceSpec) {
	*out = *in
	in.KeptnWorkloadSpec.DeepCopyInto(&out.KeptnWorkloadSpec)
	if in.TraceId != nil {
		in, out := &in.TraceId, &out.TraceId
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnWorkloadInstanceSpec.
func (in *KeptnWorkloadInstanceSpec) DeepCopy() *KeptnWorkloadInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnWorkloadInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnWorkloadInstanceStatus) DeepCopyInto(out *KeptnWorkloadInstanceStatus) {
	*out = *in
	if in.PreDeploymentTaskStatus != nil {
		in, out := &in.PreDeploymentTaskStatus, &out.PreDeploymentTaskStatus
		*out = make([]ItemStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostDeploymentTaskStatus != nil {
		in, out := &in.PostDeploymentTaskStatus, &out.PostDeploymentTaskStatus
		*out = make([]ItemStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}

	in.StartTime.DeepCopyInto(&out.StartTime)
	in.EndTime.DeepCopyInto(&out.EndTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnWorkloadInstanceStatus.
func (in *KeptnWorkloadInstanceStatus) DeepCopy() *KeptnWorkloadInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnWorkloadInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnWorkloadList) DeepCopyInto(out *KeptnWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnWorkloadList.
func (in *KeptnWorkloadList) DeepCopy() *KeptnWorkloadList {
	if in == nil {
		return nil
	}
	out := new(KeptnWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnWorkloadSpec) DeepCopyInto(out *KeptnWorkloadSpec) {
	*out = *in
	if in.PreDeploymentTasks != nil {
		in, out := &in.PreDeploymentTasks, &out.PreDeploymentTasks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostDeploymentTasks != nil {
		in, out := &in.PostDeploymentTasks, &out.PostDeploymentTasks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreDeploymentEvaluations != nil {
		in, out := &in.PreDeploymentEvaluations, &out.PreDeploymentEvaluations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostDeploymentEvaluations != nil {
		in, out := &in.PostDeploymentEvaluations, &out.PostDeploymentEvaluations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ResourceReference = in.ResourceReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnWorkloadSpec.
func (in *KeptnWorkloadSpec) DeepCopy() *KeptnWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnWorkloadStatus) DeepCopyInto(out *KeptnWorkloadStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnWorkloadStatus.
func (in *KeptnWorkloadStatus) DeepCopy() *KeptnWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemStatus) DeepCopyInto(out *ItemStatus) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.EndTime.DeepCopyInto(&out.EndTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemStatus.
func (in *ItemStatus) DeepCopy() *ItemStatus {
	if in == nil {
		return nil
	}
	out := new(ItemStatus)
	in.DeepCopyInto(out)
	return out
}
