// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fake

import (
	"context"
	lfcv1alpha3 "github.com/keptn/lifecycle-toolkit/lifecycle-operator/apis/lifecycle/v1alpha3"
	"sync"
)

// ISchedulingGatesHandlerMock is a mock implementation of common.ISchedulingGatesHandler.
//
//	func TestSomethingThatUsesISchedulingGatesHandler(t *testing.T) {
//
//		// make and configure a mocked common.ISchedulingGatesHandler
//		mockedISchedulingGatesHandler := &ISchedulingGatesHandlerMock{
//			IsSchedulingEnabledFunc: func() bool {
//				panic("mock out the IsSchedulingEnabled method")
//			},
//			RemoveGatesFunc: func(ctx context.Context, workloadInstance *lfcv1alpha3.KeptnWorkloadInstance) error {
//				panic("mock out the RemoveGates method")
//			},
//		}
//
//		// use mockedISchedulingGatesHandler in code that requires common.ISchedulingGatesHandler
//		// and then make assertions.
//
//	}
type ISchedulingGatesHandlerMock struct {
	// IsSchedulingEnabledFunc mocks the IsSchedulingEnabled method.
	IsSchedulingEnabledFunc func() bool

	// RemoveGatesFunc mocks the RemoveGates method.
	RemoveGatesFunc func(ctx context.Context, workloadInstance *lfcv1alpha3.KeptnWorkloadInstance) error

	// calls tracks calls to the methods.
	calls struct {
		// IsSchedulingEnabled holds details about calls to the IsSchedulingEnabled method.
		IsSchedulingEnabled []struct {
		}
		// RemoveGates holds details about calls to the RemoveGates method.
		RemoveGates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkloadInstance is the workloadInstance argument value.
			WorkloadInstance *lfcv1alpha3.KeptnWorkloadInstance
		}
	}
	lockIsSchedulingEnabled sync.RWMutex
	lockRemoveGates         sync.RWMutex
}

// IsSchedulingEnabled calls IsSchedulingEnabledFunc.
func (mock *ISchedulingGatesHandlerMock) IsSchedulingEnabled() bool {
	if mock.IsSchedulingEnabledFunc == nil {
		panic("ISchedulingGatesHandlerMock.IsSchedulingEnabledFunc: method is nil but ISchedulingGatesHandler.IsSchedulingEnabled was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsSchedulingEnabled.Lock()
	mock.calls.IsSchedulingEnabled = append(mock.calls.IsSchedulingEnabled, callInfo)
	mock.lockIsSchedulingEnabled.Unlock()
	return mock.IsSchedulingEnabledFunc()
}

// IsSchedulingEnabledCalls gets all the calls that were made to IsSchedulingEnabled.
// Check the length with:
//
//	len(mockedISchedulingGatesHandler.IsSchedulingEnabledCalls())
func (mock *ISchedulingGatesHandlerMock) IsSchedulingEnabledCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsSchedulingEnabled.RLock()
	calls = mock.calls.IsSchedulingEnabled
	mock.lockIsSchedulingEnabled.RUnlock()
	return calls
}

// RemoveGates calls RemoveGatesFunc.
func (mock *ISchedulingGatesHandlerMock) RemoveGates(ctx context.Context, workloadInstance *lfcv1alpha3.KeptnWorkloadInstance) error {
	if mock.RemoveGatesFunc == nil {
		panic("ISchedulingGatesHandlerMock.RemoveGatesFunc: method is nil but ISchedulingGatesHandler.RemoveGates was just called")
	}
	callInfo := struct {
		Ctx              context.Context
		WorkloadInstance *lfcv1alpha3.KeptnWorkloadInstance
	}{
		Ctx:              ctx,
		WorkloadInstance: workloadInstance,
	}
	mock.lockRemoveGates.Lock()
	mock.calls.RemoveGates = append(mock.calls.RemoveGates, callInfo)
	mock.lockRemoveGates.Unlock()
	return mock.RemoveGatesFunc(ctx, workloadInstance)
}

// RemoveGatesCalls gets all the calls that were made to RemoveGates.
// Check the length with:
//
//	len(mockedISchedulingGatesHandler.RemoveGatesCalls())
func (mock *ISchedulingGatesHandlerMock) RemoveGatesCalls() []struct {
	Ctx              context.Context
	WorkloadInstance *lfcv1alpha3.KeptnWorkloadInstance
} {
	var calls []struct {
		Ctx              context.Context
		WorkloadInstance *lfcv1alpha3.KeptnWorkloadInstance
	}
	mock.lockRemoveGates.RLock()
	calls = mock.calls.RemoveGates
	mock.lockRemoveGates.RUnlock()
	return calls
}
