---
# Source: keptn/charts/certManager/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-operator
  namespace: "helmtests"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    helm.sh/chart: cert-manager-0.1.0
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: keptn-test
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: keptn/charts/certManager/templates/certificate-operator-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificate-operator-role
  namespace: "helmtests"
  labels:
    helm.sh/chart: cert-manager-0.1.0
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: keptn-test
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
---
# Source: keptn/charts/certManager/templates/certificate-operator-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certificate-operator-rolebinding
  namespace: "helmtests"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    helm.sh/chart: cert-manager-0.1.0
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: keptn-test
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'certificate-operator-role'
subjects:
- kind: ServiceAccount
  name: 'certificate-operator'
  namespace: 'helmtests'
---
# Source: keptn/charts/certManager/templates/certificate-operator-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certificate-operator-role
  namespace: "helmtests"
  labels:
    helm.sh/chart: cert-manager-0.1.0
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: keptn-test
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - keptn-certs
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
---
# Source: keptn/charts/certManager/templates/certificate-operator-leader-election-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificate-operator-leader-election-rolebinding
  namespace: "helmtests"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    helm.sh/chart: cert-manager-0.1.0
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: keptn-test
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'leader-election-role'
subjects:
- kind: ServiceAccount
  name: 'certificate-operator'
  namespace: 'helmtests'
---
# Source: keptn/charts/certManager/templates/certificate-operator-role-binding-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificate-operator-role-binding
  namespace: "helmtests"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    helm.sh/chart: cert-manager-0.1.0
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: keptn-test
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'certificate-operator-role'
subjects:
- kind: ServiceAccount
  name: 'certificate-operator'
  namespace: 'helmtests'
---
# Source: keptn/charts/certManager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-operator
  namespace: "helmtests"
  labels:
    app.kubernetes.io/component: keptn-cert-manager
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    control-plane: certificate-operator
    helm.sh/chart: cert-manager-0.1.0
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: keptn-test
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: certificate-operator
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: keptn-test
  template:
    metadata:
      labels:
        control-plane: certificate-operator
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/instance: keptn-test
      annotations:
        kubectl.kubernetes.io/default-container: certificate-operator
    spec:
      containers:
        - args:
            - --leader-elect
          command:
            - /manager
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LABEL_SELECTOR_KEY
              value: "keptn.sh/inject-cert"
            - name: LABEL_SELECTOR_VALUE
              value: "true"
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: cluster.local
          image: ghcr.io/keptn/certificate-operator:v1.1.0
          imagePullPolicy: Always
          name: certificate-operator
          resources:
            limits:
              cpu: 25m
              memory: 64Mi
            requests:
              cpu: 5m
              memory: 16Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets: []
      securityContext:
        runAsNonRoot: true
      serviceAccountName: certificate-operator
      terminationGracePeriodSeconds: 10
