apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: pre-deployment-check-frontend
  namespace: podtato-kubectl
spec:
  function:
    httpRef:
      url: https://raw.githubusercontent.com/keptn-sandbox/lifecycle-controller/main/runtimes/deno-runtime/samples/ts/http.ts
    parameters:
      map:
        url: http://podtato-head-frontend.podtato-kubectl.svc.cluster.local:8080
