name: "Deploy Keptn on GH cluster"
description: "Creates a Kind cluster and deploys Keptn"
inputs:
  kind-version:
    required: false
    description: "Version of kind that should be used"
    # renovate: datasource=github-releases depName=kubernetes-sigs/kind
    default: "v0.24.0"
  k8s-version:
    required: false
    description: "Kubernetes version that should be used"
    # renovate: datasource=github-releases depName=kubernetes/kubernetes
    default: "v1.31.0"
  runtime_tag:
    description: "Tag for the runner image"
    required: true
  cluster-name:
    required: false
    description: "Name of the kind cluster"
    default: "test-cluster"
  values-file:
    required: false
    description: "Values file used for Keptn installation configuration"
    default: "values.yaml"
  cert-manager-io-enabled:
    required: false
    description: "Decides whether to use cert-manager.io"
    default: "cert_manager_io_off"
runs:
  using: "composite"
  steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: '**/go.sum'
        check-latest: true

    - name: Download artifacts
      uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
      with:
        path: ~/download/artifacts

    - name: "Create single kind Cluster"
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        cluster_name: ${{ inputs.cluster-name }}
        version: ${{ inputs.kind-version }}
        node_image: "kindest/node:${{ inputs.k8s-version }}"
        kubectl_version: ${{ inputs.k8s-version }}

    - name: Import images in k3d
      shell: bash
      run: |
        cd ~/download/artifacts
        for image in $(ls | grep image.tar);
        do
          echo "Importing image: $image"
          kind load image-archive $image/$image -n ${{ inputs.cluster-name }}
        done

    - name: Install cert-manager.io
      if: inputs.cert-manager-io-enabled == 'cert_manager_io_on'
      env:
        # renovate: datasource=github-releases depName=cert-manager/cert-manager
        CERT_MANAGER_IO_VERSION: "v1.16.1"
      shell: bash
      run: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/$CERT_MANAGER_IO_VERSION/cert-manager.yaml
        kubectl wait --for=condition=Available deployment/cert-manager-webhook -n cert-manager --timeout=120s
        kubectl wait --for=condition=ready pod -l app=webhook -n cert-manager --timeout=60s

        kubectl create ns keptn-system
        kubectl apply -f .github/actions/deploy-keptn-on-cluster/values/certificate.yaml

    - name: Install Keptn with helm
      env:
        RELEASE_REGISTRY: "localhost:5000/keptn"
      shell: bash
      run: |
        echo "Installing Keptn using helm"
        helm version

        helm repo add keptn "https://charts.lifecycle.keptn.sh"
        helm repo update

        for chart_dir in ./lifecycle-operator/chart \
                ./metrics-operator/chart \
                ./keptn-cert-manager/chart \
                ./chart; do
            cd "$chart_dir"
            echo "updating charts for" $chart_dir
            helm dependency update
            helm dependency build
            cd -  # Return to the previous directory
        done

        cd .github/actions/deploy-keptn-on-cluster

        export TAG=${{ inputs.runtime_tag }}
        envsubst < values/${{ inputs.values-file }} > tmp.yaml

        echo "installing with values.yaml file:"
        cat tmp.yaml

        helm install -n keptn-system --create-namespace keptn ../../../chart \
          --values ./tmp.yaml \
          --debug --wait --timeout 1m
