resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - patch: |
      - op: replace
        path: '/spec/template/spec/containers/0/image'
        value: '${RELEASE_REGISTRY}/certificate-operator:${CHART_APPVERSION}'
    target:
      kind: Deployment
      name: certificate-operator
      namespace: system
