package common

import "go.opentelemetry.io/otel/trace"

// TODO Autogenerated mock uses pointers, I changed it manually

//go:generate moq -pkg fake -skip-ensure -out ./fake/tracer.go . ITracer
type ITracer = trace.Tracer
